### ISSUE TITLE
a bug occurred , while plotting miss ratio curve

### ISSUE THREAD

**Issue by xuefarmer** [cacheMon/libCacheSim#10]
I tried to run the following code:
python3 plot_mrc_size.py --tracepath ../data/twitter_cluster52.csv --trace-format csv --trace-format-params="time-col=1,obj-id-col=2,obj-size-col=3,delimiter=," --algos=fifo,lru,lecar,s3fifo --sizes=0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.2,0.3,0.4

the error is as follows:
15:39:02: INFO [setup_utils.py:57 (setup_utils)]: 	BASEPATH: /home/xuejj21307296/libCacheSim/_build
15:39:02: INFO [setup_utils.py:58 (setup_utils)]: 	CACHESIM_PATH: /home/xuejj21307296/libCacheSim/_build/bin/cachesim
15:39:16: WARNING [plot_mrc_size.py:69 (plot_mrc_size)]: 	cachesim may have crashed with segfault
15:39:16: INFO [plot_mrc_size.py:77 (plot_mrc_size)]: 	cachesim log: [INFO]  12-04-2023 15:39:02    csv.c:150  (tid=140273216103680): detect csv trace has header 1
15:39:16: INFO [plot_mrc_size.py:77 (plot_mrc_size)]: 	cachesim log: [INFO]  12-04-2023 15:39:02 cli_reader_utils.c:262  (tid=140273216103680): calculating working set size...
15:39:16: INFO [plot_mrc_size.py:77 (plot_mrc_size)]: 	cachesim log: [INFO]  12-04-2023 15:39:03 cli_reader_utils.c:279  (tid=140273216103680): working set size: 143542 object 29227218 byte
15:39:16: INFO [plot_mrc_size.py:77 (plot_mrc_size)]: 	cachesim log: 
15:39:16: ERROR [plot_mrc_size.py:259 (plot_mrc_size)]: 	fail to compute mrc

**Comment by 1a1a11a** [comment]
The code runs fine on my end, is it possible that you do not have enough memory? 
the easiest thing to try is to use `cachesim` binary and see what error it gives.
