### ISSUE TITLE
Can't find zstd on Arch Linux

### ISSUE THREAD

**Issue by PsiACE** [cacheMon/libCacheSim#2]
I manually installed zstd using both the source code and pacman, but it doesn't seem to be working.

I fixed this with the following files.

https://github.com/facebook/folly/blob/main/CMake/FindZstd.cmake

**Comment by PsiACE** [comment]
By the way, thank you for your work. I have been conducting research in a related field recently and have read a large number of papers from you.

**Comment by 1a1a11a** [comment]
Thank you for the issue! This has been updated. Glad to know you are interested, love to meet in person one day. :)
